const Lapiceras = {
  lapicera: [
    {
      id: 1,
      cover: "./images/shops/shops-11.png",
      name: "Lapicera Azul",
      price: 50,
      discount: 40,
    },
    {
      id: 2,
      cover: "./images/shops/shops-11.png",
      name: "Lapicera Azul",
      price: 50,
      discount: 2,
    },
    {
      id: 3,
      cover: "./images/shops/shops-11.png",
      name: "Lapicera Azul",
      price: 50,
      discount: 2,
    },
    {
      id: 4,
      cover: "./images/shops/shops-11.png",
      name: "Lapicera Azul",
      price: 50,
      discount: 2,
    },
    {
      id: 5,
      cover: "./images/shops/shops-11.png",
      name: "Lapicera Azul",
      price: 50,
      discount: 2,
    },
    {
      id: 6,
      cover: "./images/shops/shops-11.png",
      name: "Lapicera Azul",
      price: 50,
      discount: 2,
    },
    {
      id: 7,
      cover: "./images/shops/shops-11.png",
      name: "Lapicera Azul",
      price: 50,
      discount: 2,
    },
    {
      id: 8,
      cover: "./images/shops/shops-11.png",
      name: "Lapicera Azul",
      price: 50,
      discount: 2,
    },
    {
      id: 9,
      cover: "./images/shops/shops-11.png",
      name: "Lapicera Azul",
      price: 50,
      discount: 2,
    },
    {
      id: 10,
      cover: "./images/shops/shops-11.png",
      name: "Lapicera Azul",
      price: 50,
      discount: 2,
    },
    {
      id: 11,
      cover: "./images/shops/shops-11.png",
      name: "Lapicera Azul",
      price: 50,
      discount: 2,
    },
    {
      id: 12,
      cover: "./images/shops/shops-11.png",
      name: "Lapicera Azul",
      price: 50,
      discount: 2,
    },
    {
      id: 13,
      cover: "./images/shops/shops-11.png",
      name: "Lapicera Azul",
      price: 50,
      discount: 2,
    },
    {
      id: 14,
      cover: "./images/shops/shops-11.png",
      name: "Lapicera Azul",
      price: 50,
      discount: 2,
    },
  ],
}
export default Lapiceras
