const Lapiceras = {
  lapicera: [
    {
      id: 11,
      cover: "./images/shops/shops-11.png",
      name: "Lapicera Azul",
      price: 50,
      discount: 40,
    },
    {
      id: 11,
      cover: "./images/shops/shops-11.png",
      name: "Lapicera Azul",
      price: 50,
      discount: 2,
    },
    {
      id: 11,
      cover: "./images/shops/shops-11.png",
      name: "Lapicera Azul",
      price: 50,
      discount: 2,
    },
    {
      id: 11,
      cover: "./images/shops/shops-11.png",
      name: "Lapicera Azul",
      price: 50,
      discount: 2,
    },
    {
      id: 11,
      cover: "./images/shops/shops-11.png",
      name: "Lapicera Azul",
      price: 50,
      discount: 2,
    },
    {
      id: 11,
      cover: "./images/shops/shops-11.png",
      name: "Lapicera Azul",
      price: 50,
      discount: 2,
    },
    {
      id: 11,
      cover: "./images/shops/shops-11.png",
      name: "Lapicera Azul",
      price: 50,
      discount: 2,
    },
    {
      id: 11,
      cover: "./images/shops/shops-11.png",
      name: "Lapicera Azul",
      price: 50,
      discount: 2,
    },
    {
      id: 11,
      cover: "./images/shops/shops-11.png",
      name: "Lapicera Azul",
      price: 50,
      discount: 2,
    },
    {
      id: 11,
      cover: "./images/shops/shops-11.png",
      name: "Lapicera Azul",
      price: 50,
      discount: 2,
    },
    {
      id: 11,
      cover: "./images/shops/shops-11.png",
      name: "Lapicera Azul",
      price: 50,
      discount: 2,
    },
    {
      id: 11,
      cover: "./images/shops/shops-11.png",
      name: "Lapicera Azul",
      price: 50,
      discount: 2,
    },
    {
      id: 11,
      cover: "./images/shops/shops-11.png",
      name: "Lapicera Azul",
      price: 50,
      discount: 2,
    },
    {
      id: 11,
      cover: "./images/shops/shops-11.png",
      name: "Lapicera Azul",
      price: 50,
      discount: 2,
    },
  ],
}
export default Lapiceras
