const Relojes = {
  relojes: [
    {
      id: 1,
      path:"/productos-relojesPared",
      cover: "./images/shops/shops-17.png",
      cover1: "./images/shops/shops-12.jpg",
      cover2: "./images/shops/shops-14.jpg",
      name: "Reloj Grande",
      description: "Este reloj de pared es un accesorio moderno y minimalista con bordes negros, hecho de plástico duro, resistente a golpes y caídas. Los números de tamaño normal son fáciles de leer, y funciona con una pila doble A. Fácil de instalar con su soporte para colgar, y su tamaño de 200x200mm lo hace perfecto para cualquier pared estándar. Un producto elegante y funcional para decorar cualquier ambiente.",
      price: "5",
      discount: "2",
    },
    {
      id: 2,
      path:"/productos-relojesPared",
      cover: "./images/shops/shops-14.png",
      name: "Reloj Romano",
      description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Vitae animi ad minima veritatis dolore. Architecto facere dignissimos voluptate fugit ratione molestias quis quidem exercitationem voluptas.",
      price: "5",
      discount: "2",
    },
    {
      id: 3,
      path:"/productos-relojesPared",
      cover: "./images/shops/shops-13.jpg",
      name: "Reloj de Cocacola V1",
      description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Vitae animi ad minima veritatis dolore. Architecto facere dignissimos voluptate fugit ratione molestias quis quidem exercitationem voluptas.",
      price: "5",
      discount: "2",
    },
    {
      id: 4,
      path:"/productos-relojesPared",
      cover: "./images/shops/shops-15.jpg",
      name: "Reloj de Cocacola V2",
      description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Vitae animi ad minima veritatis dolore. Architecto facere dignissimos voluptate fugit ratione molestias quis quidem exercitationem voluptas.",
      price: "5",
      discount: "2",
    },
    {
      id: 5,
      path:"/productos-relojesPared",
      cover: "./images/shops/shops-12.jpg",
      name: "Reloj grande",
      description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Vitae animi ad minima veritatis dolore. Architecto facere dignissimos voluptate fugit ratione molestias quis quidem exercitationem voluptas.",
      price: "5",
      discount: "2",
    },
    {
      id: 6,
      path:"/productos-relojesPared",
      cover: "./images/shops/shops-12.jpg",
      name: "Reloj grande",
      description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Vitae animi ad minima veritatis dolore. Architecto facere dignissimos voluptate fugit ratione molestias quis quidem exercitationem voluptas.",
      price: "5",
      discount: "2",
    },
    {
      id: 7,
      path:"/productos-relojesPared",
      cover: "./images/shops/shops-12.jpg",
      name: "Reloj grande",
      description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Vitae animi ad minima veritatis dolore. Architecto facere dignissimos voluptate fugit ratione molestias quis quidem exercitationem voluptas.",
      price: "5",
      discount: "2",
    },
    {
      id: 8,
      path:"/productos-relojesPared",
      cover: "./images/shops/shops-12.jpg",
      name: "Reloj grande",
      description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Vitae animi ad minima veritatis dolore. Architecto facere dignissimos voluptate fugit ratione molestias quis quidem exercitationem voluptas.",
      price: "5",
      discount: "2",
    },
    {
      id: 9,
      path:"/productos-relojesPared",
      cover: "./images/shops/shops-12.jpg",
      name: "Reloj grande",
      description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Vitae animi ad minima veritatis dolore. Architecto facere dignissimos voluptate fugit ratione molestias quis quidem exercitationem voluptas.",
      price: "5",
      discount: "2",
    },
    {
      id: 10,
      path:"/productos-relojesPared",
      cover: "./images/shops/shops-12.jpg",
      name: "Reloj grande",
      description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Vitae animi ad minima veritatis dolore. Architecto facere dignissimos voluptate fugit ratione molestias quis quidem exercitationem voluptas.",
      price: "5",
      discount: "2",
    },
    {
      id: 11,
      path:"/productos-relojesPared",
      cover: "./images/shops/shops-12.jpg",
      name: "Reloj grande",
      description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Vitae animi ad minima veritatis dolore. Architecto facere dignissimos voluptate fugit ratione molestias quis quidem exercitationem voluptas.",
      price: "5",
      discount: "2",
    },
    {
      id: 12,
      path:"/productos-relojesPared",
      cover: "./images/shops/shops-12.jpg",
      name: "Reloj grande",
      description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Vitae animi ad minima veritatis dolore. Architecto facere dignissimos voluptate fugit ratione molestias quis quidem exercitationem voluptas.",
      price: "5",
      discount: "2",
    },
    {
      id: 13,
      path:"/productos-relojesPared",
      cover: "./images/shops/shops-12.jpg",
      name: "Reloj grande",
      description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Vitae animi ad minima veritatis dolore. Architecto facere dignissimos voluptate fugit ratione molestias quis quidem exercitationem voluptas.",
      price: "5",
      discount: "2",
    },
    {
      id: 14,
      path:"/productos-relojesPared",
      cover: "./images/shops/shops-12.jpg",
      name: "Reloj grande",
      description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Vitae animi ad minima veritatis dolore. Architecto facere dignissimos voluptate fugit ratione molestias quis quidem exercitationem voluptas.",
      price: "5",
      discount: "2",
    },
  ],
}
export default Relojes