const RelojesDeMano = {
  relojesDeMano: [
    {
      id: 2,
      cover: "./images/flash/flash-2.png",
      name: "Watch",
      price: 20,
      discount: 40,
    },
    {
      id: 2,
      cover: "./images/flash/flash-2.png",
      name: "Watch",
      price: 20,
      discount: 40,
    },
    {
      id: 2,
      cover: "./images/flash/flash-2.png",
      name: "Watch",
      price: 20,
      discount: 40,
    },
    {
      id: 2,
      cover: "./images/flash/flash-2.png",
      name: "Watch",
      price: 20,
      discount: 40,
    },
    {
      id: 2,
      cover: "./images/flash/flash-2.png",
      name: "Watch",
      price: 20,
      discount: 40,
    },
    {
      id: 2,
      cover: "./images/flash/flash-2.png",
      name: "Watch",
      price: 20,
      discount: 40,
    },
    {
      id: 2,
      cover: "./images/flash/flash-2.png",
      name: "Watch",
      price: 20,
      discount: 40,
    },
    {
      id: 2,
      cover: "./images/flash/flash-2.png",
      name: "Watch",
      price: 20,
      discount: 40,
    },
    {
      id: 2,
      cover: "./images/flash/flash-2.png",
      name: "Watch",
      price: 20,
      discount: 40,
    },
    {
      id: 2,
      cover: "./images/flash/flash-2.png",
      name: "Watch",
      price: 20,
      discount: 40,
    },
    {
      id: 2,
      cover: "./images/flash/flash-2.png",
      name: "Watch",
      price: 20,
      discount: 40,
    },
    {
      id: 2,
      cover: "./images/flash/flash-2.png",
      name: "Watch",
      price: 20,
      discount: 40,
    },
    {
      id: 2,
      cover: "./images/flash/flash-2.png",
      name: "Watch",
      price: 20,
      discount: 40,
    },
    {
      id: 2,
      cover: "./images/flash/flash-2.png",
      name: "Watch",
      price: 20,
      discount: 40,
    },
  ],
}
export default RelojesDeMano
