const Relojes = {
  relojes: [
    {
      id: 15,
      cover: "./images/shops/shops-12.jpg",
      name: "Reloj Grande",
      price: "5",
      discount: "2",
    },
    {
      id: 15,
      cover: "./images/shops/shops-14.png",
      name: "Reloj Romano",
      price: "5",
      discount: "2",
    },
    {
      id: 15,
      cover: "./images/shops/shops-13.jpg",
      name: "Reloj de Cocacola V1",
      price: "5",
      discount: "2",
    },
    {
      id: 15,
      cover: "./images/shops/shops-15.jpg",
      name: "Reloj de Cocacola V2",
      price: "5",
      discount: "2",
    },
    {
      id: 15,
      cover: "./images/shops/shops-12.jpg",
      name: "Reloj grande",
      price: "5",
      discount: "2",
    },
    {
      id: 15,
      cover: "./images/shops/shops-12.jpg",
      name: "Reloj grande",
      price: "5",
      discount: "2",
    },
    {
      id: 15,
      cover: "./images/shops/shops-12.jpg",
      name: "Reloj grande",
      price: "5",
      discount: "2",
    },
    {
      id: 15,
      cover: "./images/shops/shops-12.jpg",
      name: "Reloj grande",
      price: "5",
      discount: "2",
    },
    {
      id: 15,
      cover: "./images/shops/shops-12.jpg",
      name: "Reloj grande",
      price: "5",
      discount: "2",
    },
    {
      id: 15,
      cover: "./images/shops/shops-12.jpg",
      name: "Reloj grande",
      price: "5",
      discount: "2",
    },
    {
      id: 15,
      cover: "./images/shops/shops-12.jpg",
      name: "Reloj grande",
      price: "5",
      discount: "2",
    },
    {
      id: 15,
      cover: "./images/shops/shops-12.jpg",
      name: "Reloj grande",
      price: "5",
      discount: "2",
    },
    {
      id: 15,
      cover: "./images/shops/shops-12.jpg",
      name: "Reloj grande",
      price: "5",
      discount: "2",
    },
    {
      id: 15,
      cover: "./images/shops/shops-12.jpg",
      name: "Reloj grande",
      price: "5",
      discount: "2",
    },
  ],
}
export default Relojes
